### ISSUE TITLE
Add database and logs to .gitignore

### ISSUE THREAD

**Issue by DevHyperCoder** [ahnaf-zamil/shikamaru-bot#1]
I think the owner should add the database.db and the logs and such files to the .gitignore

**Comment by DevHyperCoder** [comment]
Config files should be added to .gitignore and provide a example either in a seperate file or in the README.md or both

**Comment by ahnaf-zamil** [comment]
Hi there! Thanks for contributing to Shikamaru Bot. So first of all, this is a great idea. We should put the database and logs to gitignore. But we should keep the config files because I want the user to know what the configuration should look like. But I will make an example config file so that I don't have to keep removing the token everytime I commit to the repo. Thanks a lot!
